### ISSUE TITLE
Serving site: tasks

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/hyper-recent#25]
Tasks required to serve a (demo)  site:

- [x] A branch to build:  `main`
- [x] A build command (`npm run build`)
- [x] A directory to deploy (`/dist`)

**Comment by jvwong** [comment]
@maxkfranz these builds are failing on cloudflare (i think, can't see the logs) - maybe my buggy bash script is defeating the purpose of 'quick and dirty' and I should just turn these into nodeJS commander CLI programs?

**Comment by maxkfranz** [comment]
Yes, it's probably simpler to use node.  It looks like the scripts are fairly simple, so hopefully it's straightforward to convert them.  I pushed some date fixes to your PR branch, so that part should be resolved already.

**Comment by jvwong** [comment]
OK I will translate into commander programs.

**Comment by jvwong** [comment]
OK thanks!
