### ISSUE TITLE
Make fresh data available regularly

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/hyper-recent#41]
Background: Currently we retrieve the article data manually and save it to local file (e.g. `data-search.js`). On build (e.g. `npm run build` or `npm run watch`), the data file is directly imported as a JS module and the associated data is bundled with the App.

Problem: The data is currently fixed. The intention is for the App to show updated article information (e.g. daily). To accomplish this, it will be necessary to make bundling and serving the App (i.e. on Cloudflare) separate from the article data it uses. 

Goal: Make the App retrieve the article data file from an external source.

---

Q: What are the applicable constraints, e.g. compatibility or performance?

A: The source of the data should enable browsers to access the information. For instance, a binary file associated with a GitHub release does not provide for Cross-Origin Resource Sharing (CORS). A temporary solution is to point the app at a file in the remote (e.g.   https://raw.githubusercontent.com/PathwayCommons/hyper-recent/main/example-data/data.json) and find a suitable data store (see below).

- References
  -  Data repository to check: https://www.cloudflare.com/en-ca/products/workers-kv/

**Comment by jvwong** [comment]
> * (3) Make the file processing generation part of the Cloudflare pages build script
>   
>   * Github actions could kick off a build via [a deploy hook](https://developers.cloudflare.com/pages/platform/deploy-hooks/)
>   * [CF pages has a 20 minute build limit time](https://developers.cloudflare.com/pages/platform/limits) -- probably enough
>   * Pros: even simpler than (1)
>   * Cons: handling history of files requires an extra step or you need to build N days of data each time if the dashboard goes N days back

I did a couple of runs of `data-search.js` locally and it's about 2.5 minutes (0.23 MB file for 1 popular topic "alzheimers" over 1 month).  Maybe we can give the (3) CF-build a try.

**Comment by maxkfranz** [comment]
Probably good enough for now.

For future:  Remotes builds are usually slower than local.  I wouldn't be surprised if alzheimers/1mo took ~10 min.

**Comment by jvwong** [comment]
PR #42 build took 3m 48s to complete (1 topic)
